### ISSUE TITLE
[feature request] LuaJIT

### ISSUE THREAD

**Issue by nonchip** [stetre/luajack#1]
is it possible (if yes: how?) to build this against luajit?

**Comment by stetre** [comment]
Nope. This is for Lua, while LuaJIT is a different language by now. At least afaik. Honestly I'm not following LuaJIT evolution... I find it easier to stick with standard Lua and, if needed, deal with performance issues by just going back to C through the Lua C API.

**Comment by nonchip** [comment]
LuaJIT is *not* a different language, but just another compiler. also APIcompatible on the C side. and way faster than context switching using the C api. if you've done things "right" (according to current lua manual; using `luaL_…` functions in favor over their deprecated counterparts, etc), it should be possible to just change the makefile.

**Comment by nonchip** [comment]
alternatively: I've now built a LuaJIT FFI cdef as part of [nonchip/yabaplayer](https://github.com/nonchip/yabaplayer), if anyone else just needs that FFI part, and not your whole project. but would've been nice to see this running with LuaJIT too

**Comment by stetre** [comment]
Let me put it in another way: LuaJIT is a different "object" from Lua, with an independent life since (if I remember well) version 5.1 or so. I may be wrong because I have not investigated directly *not being interested at all*, but I heard it from Roberto Ierusalemischky's voice in an interview and I think I can trust him on the matter. LuaJack is built on top of the Lua 5.3 package, so if LuaJIT is really compatible, there should be no problem at all(but we know that there are...)

As for the "deprecated functions" I don't know what you are talking about: luaL_ functions do not deprecate other "counterparts", they are only convenience macros. 

As for the performance, the performance sensitive part here is the signal processing, and with LuaJack you can do the bulk of it completely in C. Is LuaJIT faster than C? But, again, if you are developing applications where you need really high performance, maybe there is no point in using scripting languages in the first place...

**Comment by nonchip** [comment]
> (stuff about project management)

that's true, but irrelevant to the issue. LLVM is also independent to GCC, and both do a decent job at compiling C. you're mixing up the specs with the reference implementation here. LuaJIT isn't the reference implementation of `lua[c]`, of course, but it still implements the language Lua.

> LuaJack is built on top of the Lua 5.3 package, so if LuaJIT is really compatible, there should be no problem at all

LuaJIT is currently 100% API compatible to Lua 5.1 and on top of that implements most 5.2 features.

> (but we know that there are...)

how do we know that? I don't see any, except from your build system being relatively strict about which lib to link against.

> As for the "deprecated functions" I don't know what you are talking about: luaL_ functions do not deprecate other "counterparts", they are only convenience macros.

that's true, but e.g. `lua_newstate` expects an allocator or falls back to `realloc`, while `luaL_newstate` actually ships its own (optimized) allocator better suitable for 64bit systems in most implementations.

> As for the performance, the performance sensitive part here is the signal processing, and with LuaJack you can do the bulk of it completely in C.

then I don't really get the point of building Lua bindings for it.

> Is LuaJIT faster than C?

no, but almost as fast (see e.g. http://lua-users.org/lists/lua-l/2009-06/msg00071.html, and that was just a 2.0 RC).

> But, again, if you are developing applications where you need really high performance, maybe there is no point in using scripting languages in the first place...

that's why I'd like to use LuaJIT, which isn't an interpreter, but a compiler.

the language you use doesn't affect the performance at all (except for some missing crucial features, e.g. brainfuck would of course be slower than others at doing the same task, because it's missing most common high level language operators), but the implementation does.

**Comment by stetre** [comment]
It is luaL_newstate() to fall back to the realloc based allocator, actually. At least in standard Lua (both in the code and in the manual). If in LuaJIT this is different, maybe it is because LuaJIT is not Lua...

Stuff about project management: neither the project manager nor the customer of this project asked for LuaJIT support. Had they, arguing that LuaJIT and Lua are the same language, I would have refused the job (btw, they did not because both are myself).

I can understand why you'd like to use LuaJIT, but I have a different philosophy: if I do something in Lua instead of C, it is because I can/am willing to pay the performance price of an interpreted language for the benefits it gives me in return. Otherwise I just use C and avoid the contortion of choosing an interpreted language, but then replacing it with with an "almost" compatible (at least potentially divergent) implementation in order to gain like-C performance. Languages like Lua allow you to easily integrate scripting parts and C parts, so there is no need for contortions...

**Comment by nonchip** [comment]
> It is luaL_newstate() to fall back to the realloc based allocator, actually. At least in standard Lua (both in the code and in the manual).

ok, yeah, I misread that, but:

> If in LuaJIT this is different, maybe it is because LuaJIT is not Lua...

wrong. LuaJIT is not the Lua standard distribution, but still Lua. because Lua is a language, not a program. or do you tell people "Webster's not english, because Oxford's says some word is written differently"?

> Stuff about project management: neither the project manager nor the customer of this project asked for LuaJIT support. Had they, arguing that LuaJIT and Lua are the same language, I would have refused the job (btw, they did not because both are myself).

I meant the stuff about Lua stdlib vs LuaJIT project management. they're both different projects, but that doesn't mean they're not both implementations of the Lua language.

also, you're getting pretty defensive there, so let me put this straight: I didn't mean to offend you by telling you how to do stuff, I simply thought LuaJIT support on this project would be a great feature and asked whether a) you think it's possible and/or b) you're going to do it. which you don't want to, and that's perfectly fine, but I disagree with the point "it would not be Lua", because it still would be, just another implementation.

> I can understand why you'd like to use LuaJIT, but I have a different philosophy […]

I understand that too, and by looking at your code again I'd agree that while making it compatible to LuaJIT shouldn't be too hard, it'd be a hell of work to make it make use of the FFI api (which would be one of the most important reasons, apart from the performance issue, to choose LuaJIT over the stdlib).

so, to conclude this: in the project I linked above I found a pretty simple FFI cdef for libjack (by using gcc's preprocessor to parse a header file containing some includes into a format understandable by LuaJIT's `require'ffi'.cdef`). so I guess I'll stick to that instead for developing in Lua (or actually MoonScript in that project's case), because I just have a completely different use case from your's (which is more "script a C program using Lua", while I "load C libs in a Lua program").

**Comment by stetre** [comment]
I see that you have strong opinions on this "LuaJIT is the same as Lua" subject. May I suggest you to listen to Roberto's opinion? You can find it here, together with a few interesting considerations on performance:
https://www.youtube.com/watch?v=I7__DfWfYd8&feature=youtu.be&t=1246

As for the points a) and b), the precise answers are a) maybe, when LuaJIT will be aligned with Lua 5.3, and b) no, because it would add nothing to it (in my view, of course) and If I do it, then I would have to follow two objects with divergent paths. I do this stuff for pleasure, not for torture...

**Comment by nonchip** [comment]
well, according to Mike Pall on http://luajit.org/luajit.html, "LuaJIT is a Just-In-Time Compiler (JIT) for the Lua programming language.", and he builds the thing, so he should know what he's trying to achieve.

Of course they are two different projects, but that's not the point, because Lua as a language is defined by its specification (mainly syntax, and semantics like defined keywords), while `lua`/`liblua` and `luajit`/`libluajit` are just two different implementations of that spec. there are others btw (e.g. LLVM-Lua, LuaJ) which don't depend on `liblua` and are seperate projects all implementing the Lua language.
(I mean even sitting down with a pen and paper to "code" and your brain to "execute" stuff would still follow the language. which I btw do sometimes because Lua is a really easy to read language, so can be used as a pseudocode to explain algorithms to people.)


It's true that LuaJIT only fully supports Lua 5.1, and I really hope that'll be fixed anytime soon, so of course, if you depend on 5.3-only features, it'd be too much work to backport your codebase.

and if you say you want to stick with `liblua` only that's of course your right to do, it just wasn't clear to me, because when you initially said "LuaJIT is different from Lua" I thought you meant them being two different languages, not two different implementations. switching from `liblua` to `libluajit` would mean no changes to the Lua code (if it's 5.1 compatible or we wait for LuaJIT to catch up to 5.3, of course), but could mean some changes on the C api side (like you really want to use `luaL_newstate` with `libluajit`, because it does some really fancy optimizations in that macro) and of course in the build system.

**Comment by stetre** [comment]
I actually want to use anything Lua (language+library) provides, without worrying if what I use is compatible with any other Lua implementation that claims to be Lua-compatible.

If we consider Lua only as a language defined by its syntax and semantics (+pragmatics), and we have different compatible implementations of the Lua interpreter (compiler or whatever), we can expect to take a Lua script and use it with any of them without changing the script. But this is only half of the story, because Lua is not only the language. It has to interfaces: one towards the scripts, and another one towards C modules. Especially when it comes to binding modules which have to be written in C, like LuaJack, "standard Lua" is the library + its header files (i.e. the C-API) on top of which these modules have to be developed. If an alternative Lua implementation (luajit or, say, luawhatever) is a truly compatible replacement for the standard one, you should be able to take any module developed for liblua, change -llua to -lluawhatever in the makefile (and possibly the include path for the .h files), compile it and use it without changing a line of code in the module. If it does not, and if you need to ask the developers of the module if and how you can make this work, or if you start asking "have you used this or that feature", this simply means that the alternative is not fully compatible.

If you think about it, the answer to the question "Can the LuaXxx module be compiled against luawhatever, which is a compatible alternative to liblua?" is in the question itself.

**Comment by dromer** [comment]
Hmm, I was very much hoping that this library would work with luajit.
I'd like to use jack in löve2d and lövr, which are both luajit.

Since I'm also working on ffi bindings to lilv I'll have a look at @nonchip project instead for now.

**Comment by stetre** [comment]
Unfortunately this is a lua binding library, and luajit is not lua, even though it started as a compatible implementation.

On the other hand, one of the selling points of luajit is the FFI which should make binding libraries like this one unnecessary (/s).

**Comment by dromer** [comment]
Well, one of the selling points of doing straight c bindings is that they could work in both lua and luajit implementations of the language.

The main issue I ran into, trying to get your code to work with luajit, is repeated usage of certain specific evaluations in c-macros. In luajit these evaluations are void, instead of int, which means the macro compiler cannot resolve them.

If I feel masochistic I will see if I can expand on these macros explicitly/manually, even though it makes the code a bit more unwieldy to read/maintain.

**Comment by stetre** [comment]
If you feel masochistic, you can do something even more exciting. You can choose to use a language fork (or products that rely on it) and then expect compatibility with the main branch (or with products that rely on it) for years to come.

**Comment by nonchip** [comment]
and if you feel like being an ass you make fun of people instead of even trying to understand what they asked for.

**Comment by stetre** [comment]
> and if you feel like being an ass you make fun of people instead of even trying to understand what they asked for.

Thank you for the hint, it might come in handy.

As you may see in the other discussions in my repos' issues I usually don't feel like being an ass, but, you know, at times people really _ask for_ it.
